version: 2

jobs:
    build:
        docker:
          - image: docker:stable-git
        steps:
            - checkout
            - run: apk --update add make
            - setup_remote_docker:
                version: 17.10.0-ce
            - run: make ci-docker-build

    deploy:
        docker:
          - image: docker:stable-git
        steps:
            - checkout
            - run: apk --update add make
            - setup_remote_docker:
                version: 17.10.0-ce
            - run: make ci-docker-build
            - run: make ci-docker-push

workflows:
  version: 2
  development:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  deployment:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
